<?php
add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_5c5d6f174d976',
	'title' => 'Page Builder',
	'fields' => array(
		array(
			'key' => 'field_5c5f35e8db2b5',
			'label' => 'Content Elements',
			'name' => 'content_elements',
			'aria-label' => '',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layouts' => array(
				'layout_65a10ff11f92e' => array(
					'key' => 'layout_65a10ff11f92e',
					'name' => 'herobanners',
					'label' => 'Herobanners',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_65a10ff11f92f',
							'label' => 'Full Width',
							'name' => 'full_width',
							'aria-label' => '',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'ui_on_text' => '',
							'ui_off_text' => '',
							'ui' => 1,
						),
						array(
							'key' => 'field_65a10ff11f930',
							'label' => 'Herobanner',
							'name' => 'herobanner',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'block',
							'min' => 1,
							'max' => 4,
							'collapsed' => 'field_5c5e8476f8c16',
							'button_label' => 'Add Teaser',
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_65a10ff11f931',
									'label' => 'Herobanner Title',
									'name' => 'herobanner_title',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'parent_repeater' => 'field_65a10ff11f930',
								),
								array(
									'key' => 'field_65a10ff11f932',
									'label' => 'Herobanner Image',
									'name' => 'herobanner_image',
									'aria-label' => '',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
									'preview_size' => 'medium',
									'parent_repeater' => 'field_65a10ff11f930',
								),
								array(
									'key' => 'field_65a10ff11f933',
									'label' => 'Herobanner Link',
									'name' => 'herobanner_link',
									'aria-label' => '',
									'type' => 'link',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'parent_repeater' => 'field_65a10ff11f930',
								),
								array(
									'key' => 'field_65a10ff11f934',
									'label' => 'Herobanner Button',
									'name' => 'herobanner_button',
									'aria-label' => '',
									'type' => 'true_false',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'message' => 'Show additional Button on Herobanner?',
									'default_value' => 0,
									'ui_on_text' => '',
									'ui_off_text' => '',
									'ui' => 1,
									'parent_repeater' => 'field_65a10ff11f930',
								),
								array(
									'key' => 'field_65a10ff11f935',
									'label' => 'Herobanner Button Text',
									'name' => 'herobanner_button_text',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_65a10ff11f934',
												'operator' => '==',
												'value' => '1',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'parent_repeater' => 'field_65a10ff11f930',
								),
							),
						),
						array(
							'key' => 'field_65a10ff11f936',
							'label' => 'Herobanner Height',
							'name' => 'herobanner_height',
							'aria-label' => '',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'banner_big' => 'Big',
								'banner_small' => 'Small',
							),
							'default_value' => 'banner_big',
							'return_format' => 'value',
							'allow_null' => 0,
							'other_choice' => 0,
							'layout' => 'horizontal',
							'save_other_choice' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'5c5f3600ed8d6' => array(
					'key' => '5c5f3600ed8d6',
					'name' => 'teasers',
					'label' => 'Teasers',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_5c5f2e292cb56',
							'label' => 'Full Width',
							'name' => 'full_width',
							'aria-label' => '',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'ui' => 1,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
						array(
							'key' => 'field_5c5e877320abe',
							'label' => 'Teaser',
							'name' => 'teaser',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => 'field_5c5e8476f8c16',
							'min' => 1,
							'max' => 4,
							'layout' => 'block',
							'button_label' => 'Add Teaser',
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_5c5e8476f8c16',
									'label' => 'Teaser Title',
									'name' => 'teaser_title',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'parent_repeater' => 'field_5c5e877320abe',
								),
								array(
									'key' => 'field_5c5e848cf8c17',
									'label' => 'Teaser Image',
									'name' => 'teaser_image',
									'aria-label' => '',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
									'preview_size' => 'medium',
									'parent_repeater' => 'field_5c5e877320abe',
								),
								array(
									'key' => 'field_5c5e85d8f8c1a',
									'label' => 'Teaser Link',
									'name' => 'teaser_link',
									'aria-label' => '',
									'type' => 'link',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'parent_repeater' => 'field_5c5e877320abe',
								),
								array(
									'key' => 'field_5c5e8606f8c1b',
									'label' => 'Teaser Button',
									'name' => 'teaser_button',
									'aria-label' => '',
									'type' => 'true_false',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'message' => 'Show additional Button on Teaser?',
									'default_value' => 0,
									'ui' => 1,
									'ui_on_text' => '',
									'ui_off_text' => '',
									'parent_repeater' => 'field_5c5e877320abe',
								),
								array(
									'key' => 'field_5c5e8657f8c1c',
									'label' => 'Teaser Button Text',
									'name' => 'teaser_button_text',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_5c5e8606f8c1b',
												'operator' => '==',
												'value' => '1',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'parent_repeater' => 'field_5c5e877320abe',
								),
							),
						),
						array(
							'key' => 'field_5c608d4a1f8e1',
							'label' => 'Teaser Height',
							'name' => 'teaser_height',
							'aria-label' => '',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'teaser_big' => 'Big',
								'teaser_small' => 'Small',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'default_value' => 'teaser_big',
							'layout' => 'horizontal',
							'return_format' => 'value',
							'save_other_choice' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_65a13553f77ef' => array(
					'key' => 'layout_65a13553f77ef',
					'name' => 'textblock',
					'label' => 'Textblock',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_65a13553f77f0',
							'label' => 'Textblock Headline',
							'name' => 'textblock_headline',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_65a13553f77f1',
							'label' => 'Textblock',
							'name' => 'textblock',
							'aria-label' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
						array(
							'key' => 'field_65a13663f77f6',
							'label' => 'Textblock Image',
							'name' => 'textblock_image',
							'aria-label' => '',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'preview_size' => 'medium',
						),
						array(
							'key' => 'field_65a136bbf77f7',
							'label' => 'Textblock Image Position',
							'name' => 'textblock_image_position',
							'aria-label' => '',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'image-left: Left' => 'image-left: Left',
								'image-right: Right' => 'image-right: Right',
							),
							'default_value' => 'image-right',
							'return_format' => 'value',
							'allow_null' => 0,
							'other_choice' => 0,
							'layout' => 'vertical',
							'save_other_choice' => 0,
						),
						array(
							'key' => 'field_65a13553f77f4',
							'label' => 'Colored Background',
							'name' => 'colored_background_textblock',
							'aria-label' => '',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'ui_on_text' => '',
							'ui_off_text' => '',
							'ui' => 1,
						),
						array(
							'key' => 'field_65a1478a94544',
							'label' => 'Background Width',
							'name' => 'background_width_textblock',
							'aria-label' => '',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_65a13553f77f4',
										'operator' => '==',
										'value' => '1',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'regular' => 'Regular',
								'breakout' => 'Breakout',
								'full-width content-grid' => 'Full Width',
							),
							'default_value' => 'regular',
							'return_format' => 'value',
							'allow_null' => 0,
							'other_choice' => 0,
							'layout' => 'vertical',
							'save_other_choice' => 0,
						),
						array(
							'key' => 'field_65a13553f77f5',
							'label' => 'Custom Color',
							'name' => 'custom_color_textblock',
							'aria-label' => '',
							'type' => 'color_picker',
							'instructions' => 'Pick a Color for the background of this elemet here ... if no color is picked, the default theme color (BG-light) gets used.',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_65a13553f77f4',
										'operator' => '==',
										'value' => '1',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'enable_opacity' => 0,
							'return_format' => 'string',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5c5f3f6236b22' => array(
					'key' => 'layout_5c5f3f6236b22',
					'name' => 'products',
					'label' => 'Products',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_5c5dfe298b9f0',
							'label' => 'Products Headline',
							'name' => 'products_headline',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5c5dfe5f8b9f1',
							'label' => 'Product Type',
							'name' => 'product_type',
							'aria-label' => '',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'sale_products' => 'Sale Products',
								'bestseller_products' => 'Bestseller Products',
								'new_products' => 'New Product',
								'category_products' => 'Product Category',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'default_value' => '',
							'layout' => 'vertical',
							'return_format' => 'value',
							'save_other_choice' => 0,
						),
						array(
							'key' => 'field_5f52b8fc64963',
							'label' => 'Product Category',
							'name' => 'product_category',
							'aria-label' => '',
							'type' => 'taxonomy',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5c5dfe5f8b9f1',
										'operator' => '==',
										'value' => 'category_products',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'taxonomy' => 'product_cat',
							'field_type' => 'select',
							'allow_null' => 0,
							'add_term' => 1,
							'save_terms' => 0,
							'load_terms' => 0,
							'return_format' => 'id',
							'multiple' => 0,
							'bidirectional_target' => array(
							),
						),
						array(
							'key' => 'field_5c5fde1af2a9e',
							'label' => 'Products Number',
							'name' => 'products_number',
							'aria-label' => '',
							'type' => 'radio',
							'instructions' => 'How Many Products in that Row?',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								1 => '1',
								2 => '2',
								3 => '3',
								4 => '4',
								6 => '6',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'default_value' => 4,
							'layout' => 'horizontal',
							'return_format' => 'value',
							'save_other_choice' => 0,
						),
						array(
							'key' => 'field_5c602cf5cad4e',
							'label' => 'Products Button',
							'name' => 'products_button',
							'aria-label' => '',
							'type' => 'true_false',
							'instructions' => 'Show Button underneath Product Row?',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'ui' => 1,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
						array(
							'key' => 'field_5c602d3acad4f',
							'label' => 'Products Button Link',
							'name' => 'products_button_link',
							'aria-label' => '',
							'type' => 'link',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5c602cf5cad4e',
										'operator' => '==',
										'value' => '1',
									),
								),
							),
							'wrapper' => array(
								'width' => '45',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5c609ccec3538' => array(
					'key' => 'layout_5c609ccec3538',
					'name' => 'posts',
					'label' => 'Posts',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_5c609ccec3539',
							'label' => 'Posts Headline',
							'name' => 'posts_headline',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5c609ccec353a',
							'label' => 'Posts Type',
							'name' => 'posts_type',
							'aria-label' => '',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'latest_pots' => 'Latest Posts',
								'featured_pots' => 'Featured Posts',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'default_value' => '',
							'layout' => 'vertical',
							'return_format' => 'value',
							'save_other_choice' => 0,
						),
						array(
							'key' => 'field_5c609ccec353b',
							'label' => 'Posts Number',
							'name' => 'posts_number',
							'aria-label' => '',
							'type' => 'radio',
							'instructions' => 'How Many Posts in that Row?',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								1 => '1',
								2 => '2',
								3 => '3',
								4 => '4',
								5 => '5',
								6 => '6',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'default_value' => 4,
							'layout' => 'horizontal',
							'return_format' => 'value',
							'save_other_choice' => 0,
						),
						array(
							'key' => 'field_5c609ccec353c',
							'label' => 'Posts Button',
							'name' => 'posts_button',
							'aria-label' => '',
							'type' => 'true_false',
							'instructions' => 'Show Button underneath Posts Row?',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'ui' => 1,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
						array(
							'key' => 'field_5c609ccfc353d',
							'label' => 'Posts Button Link',
							'name' => 'posts_button_link',
							'aria-label' => '',
							'type' => 'link',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5c609ccec353c',
										'operator' => '==',
										'value' => '1',
									),
								),
							),
							'wrapper' => array(
								'width' => '45',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5c71c986504d8' => array(
					'key' => 'layout_5c71c986504d8',
					'name' => 'accordion',
					'label' => 'Accordion',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_5c71d5cef692b',
							'label' => 'Full Width Accordion',
							'name' => 'full_width_accordion',
							'aria-label' => '',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'ui' => 1,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
						array(
							'key' => 'field_5c71de7ec9487',
							'label' => 'Accordion Headline',
							'name' => 'accordion_headline',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5c71d7c3d445f',
							'label' => 'Accordion Columns',
							'name' => 'accordion_columns',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => 1,
							'max' => 3,
							'layout' => 'table',
							'button_label' => 'Add Accordion Cloumn',
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_5c71c9b1504d9',
									'label' => 'Accordion Elements',
									'name' => 'accordion_elements',
									'aria-label' => '',
									'type' => 'repeater',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'collapsed' => '',
									'min' => 0,
									'max' => 0,
									'layout' => 'row',
									'button_label' => 'Add Accordion Element',
									'rows_per_page' => 20,
									'sub_fields' => array(
										array(
											'key' => 'field_5c71ca0b504da',
											'label' => 'Accordion Title',
											'name' => 'accordion_title',
											'aria-label' => '',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'maxlength' => '',
											'parent_repeater' => 'field_5c71c9b1504d9',
										),
										array(
											'key' => 'field_5c71ca47504db',
											'label' => 'Accordion Text',
											'name' => 'accordion_text',
											'aria-label' => '',
											'type' => 'textarea',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
											'maxlength' => '',
											'rows' => '',
											'new_lines' => '',
											'parent_repeater' => 'field_5c71c9b1504d9',
										),
									),
									'parent_repeater' => 'field_5c71d7c3d445f',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5c5f3f9836b23' => array(
					'key' => 'layout_5c5f3f9836b23',
					'name' => 'services',
					'label' => 'Services',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_5c5f3148ec502',
							'label' => 'Services Headline',
							'name' => 'services_headline',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5c5dfccc1d3af',
							'label' => 'Service',
							'name' => 'service',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => 0,
							'max' => 4,
							'layout' => 'table',
							'button_label' => 'Add Row',
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_5c5dfcfc1d3b0',
									'label' => 'Service Title',
									'name' => 'service_title',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'parent_repeater' => 'field_5c5dfccc1d3af',
								),
								array(
									'key' => 'field_5c5dfd1b1d3b1',
									'label' => 'Service Image',
									'name' => 'service_image',
									'aria-label' => '',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'preview_size' => 'medium',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => 'jpeg,jpg,png,svg',
									'parent_repeater' => 'field_5c5dfccc1d3af',
								),
								array(
									'key' => 'field_5c5dfd711d3b2',
									'label' => 'Service Link',
									'name' => 'service_link',
									'aria-label' => '',
									'type' => 'link',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'url',
									'parent_repeater' => 'field_5c5dfccc1d3af',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5f4a004ca238c' => array(
					'key' => 'layout_5f4a004ca238c',
					'name' => 'brands',
					'label' => 'Brands',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_5f4a004ca238d',
							'label' => 'Brands Headline',
							'name' => 'brands_headline',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5f4a004ca238e',
							'label' => 'Brand',
							'name' => 'brand',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => 0,
							'max' => 6,
							'layout' => 'table',
							'button_label' => 'Add Row',
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_5f4a004ca238f',
									'label' => 'Brand Title',
									'name' => 'brand_title',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'parent_repeater' => 'field_5f4a004ca238e',
								),
								array(
									'key' => 'field_5f4a004ca2390',
									'label' => 'Brand Image',
									'name' => 'brand_image',
									'aria-label' => '',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'preview_size' => 'medium',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => 'jpeg,jpg,png,svg',
									'parent_repeater' => 'field_5f4a004ca238e',
								),
								array(
									'key' => 'field_5f4a004ca2391',
									'label' => 'Brand Link',
									'name' => 'brand_link',
									'aria-label' => '',
									'type' => 'link',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'url',
									'parent_repeater' => 'field_5f4a004ca238e',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5f1a8dc67f8d6' => array(
					'key' => 'layout_5f1a8dc67f8d6',
					'name' => 'codesnippet',
					'label' => 'Codesnippet',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_5f1a8de97f8d7',
							'label' => 'Rawcode',
							'name' => 'rawcode',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5f1a9da72d581' => array(
					'key' => 'layout_5f1a9da72d581',
					'name' => 'shortcode',
					'label' => 'Shortcode',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_5f1aa1a88bcc4',
							'label' => 'Shortcode Headline',
							'name' => 'shortcode_headline',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5f1a9db32d582',
							'label' => 'Shortcodeblock',
							'name' => 'shortcodeblock',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'insert shortcode here ...',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5f1bece59877f',
							'label' => 'Full Width Background?',
							'name' => 'full_width_bg_shortcode',
							'aria-label' => '',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'ui' => 0,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
						array(
							'key' => 'field_5f1bf709b4088',
							'label' => 'Full Width Content?',
							'name' => 'full_width_content_shortcode',
							'aria-label' => '',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'ui' => 0,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
						array(
							'key' => 'field_5f1bed1f98780',
							'label' => 'Colored Background Shortcode',
							'name' => 'colored_background_shortcode',
							'aria-label' => '',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'ui' => 1,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
						array(
							'key' => 'field_5f1bed8698781',
							'label' => 'Custom Color Shortcode',
							'name' => 'custom_color_shortcode',
							'aria-label' => '',
							'type' => 'color_picker',
							'instructions' => 'Pick a Color for the background of this elemet here ... if no color is picked, the default theme color (BG-light) gets used.',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5f1bed1f98780',
										'operator' => '==',
										'value' => '1',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'enable_opacity' => false,
							'return_format' => 'string',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5f54a3a3aa6ac' => array(
					'key' => 'layout_5f54a3a3aa6ac',
					'name' => 'customcode',
					'label' => 'Customcode',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_5f54a3a3aa6ad',
							'label' => 'Customcode Headline',
							'name' => 'customcode_headline',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5f54a3a3aa6ae',
							'label' => 'Customcodecodeblock',
							'name' => 'customcodecodeblock',
							'aria-label' => '',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => '',
						),
						array(
							'key' => 'field_5f54a3a3aa6af',
							'label' => 'Full Width Background?',
							'name' => 'full_width_bg_customcode',
							'aria-label' => '',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'ui' => 0,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
						array(
							'key' => 'field_5f54a3a3aa6b0',
							'label' => 'Full Width Content?',
							'name' => 'full_width_content_customcode',
							'aria-label' => '',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'ui' => 0,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
						array(
							'key' => 'field_5f54a3a3aa6b1',
							'label' => 'Colored Background',
							'name' => 'colored_background_customcode',
							'aria-label' => '',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'ui' => 1,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
						array(
							'key' => 'field_5f54a3a3aa6b2',
							'label' => 'Custom Color',
							'name' => 'custom_color_customcode',
							'aria-label' => '',
							'type' => 'color_picker',
							'instructions' => 'Pick a Color for the background of this elemet here ... if no color is picked, the default theme color (BG-light) gets used.',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5f54a3a3aa6b1',
										'operator' => '==',
										'value' => '1',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'enable_opacity' => false,
							'return_format' => 'string',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5f54a78339395' => array(
					'key' => 'layout_5f54a78339395',
					'name' => 'signupform',
					'label' => 'Signupform',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_5f54a78339396',
							'label' => 'Signupform Headline',
							'name' => 'signupform_headline',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5f54a78339397',
							'label' => 'Signupform html',
							'name' => 'signupform_html',
							'aria-label' => '',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => '',
						),
						array(
							'key' => 'field_5f54a78339398',
							'label' => 'Full Width Background?',
							'name' => 'full_width_bg_signupform',
							'aria-label' => '',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'ui' => 0,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
						array(
							'key' => 'field_5f54a7833939a',
							'label' => 'Colored Background',
							'name' => 'colored_background_signupform',
							'aria-label' => '',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'ui' => 1,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
						array(
							'key' => 'field_5f54a7833939b',
							'label' => 'Custom Color',
							'name' => 'custom_color_signupform',
							'aria-label' => '',
							'type' => 'color_picker',
							'instructions' => 'Pick a Color for the background of this elemet here ... if no color is picked, the default theme color (BG-light) gets used.',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5f54a7833939a',
										'operator' => '==',
										'value' => '1',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'enable_opacity' => false,
							'return_format' => 'string',
						),
						array(
							'key' => 'field_5f54a7fd3939c',
							'label' => 'Signupform Info Text',
							'name' => 'signupform_info_text',
							'aria-label' => '',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => '',
						),
						array(
							'key' => 'field_5f54a8283939d',
							'label' => 'Signupform Legal Text',
							'name' => 'signupform_legal_text',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5f6d9f5896759',
							'label' => 'Signupform Legal Text Link',
							'name' => 'signupform_legal_text_link',
							'aria-label' => '',
							'type' => 'page_link',
							'instructions' => 'Please select the Page with the Data Protection Declaration',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'post_type' => array(
								0 => 'page',
							),
							'taxonomy' => '',
							'allow_null' => 0,
							'allow_archives' => 1,
							'multiple' => 0,
						),
						array(
							'key' => 'field_5f54a83d3939e',
							'label' => 'Signupform Image',
							'name' => 'signupform_image',
							'aria-label' => '',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
			),
			'min' => 1,
			'max' => '',
			'button_label' => 'Add Content Elements',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'default',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => 'a kinda page builder',
	'show_in_rest' => 0,
) );
} );


